fn main() {
    let manifest = tauri_build::AppManifest::new().commands(&[
        "chat_context_preview",
        "memory_policy_set",
        "memory_list",
        "memory_mutate",
        "chat_context_epoch",
        "memory_export",
        "personal_memory_overview",
        "personal_memory_recall",
        "personal_memory_detail",
        "personal_memory_policy_set",
        "guide_status",
        "guide_complete",
        "voice_probe",
        "voice_cancel",
        "voice_key_set",
        "model_settings_get",
        "model_settings_save",
        "model_key_set",
        "model_key_delete",
        "chat_config",
        "chat_history",
        "chat_clear",
        "chat_generate",
        "chat_cancel",
        "get_runtime_info",
        "list_tasks",
        "create_task",
        "cancel_task",
        "pet_action",
        "set_pet_regions",
    ]);
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(manifest))
        .expect("failed to build desktop application manifest");
}
